### ISSUE TITLE
Map not working great on mobile

### ISSUE THREAD

**Issue by tvb** [meeuw/legocityundercovermap#6]
I don't know if it's a simple fix, but the map is difficult to navigate on mobile (iOS).

**Comment by meeuw** [comment]
Hi @tvb thanks for your issue report!

Could you please be a bit more specific on what makes it difficult to navigate? For me it okayish on Android with Google Chrome (I don't own any iOS devices so I cannot test).

I do agree that the buttons are a bit small, is that what you experience?

**Comment by tvb** [comment]
![image](https://github.com/meeuw/legocityundercovermap/assets/1263414/18f1352a-9b0d-4bc5-af39-37b0b24837b0)

See attachment. I can't disable the overlay

**Comment by tvb** [comment]
@meeuw Got time to fix this?

**Comment by meeuw** [comment]
Hi @tvb, it's a bit of guessing but I've resized the legend box a bit (this seems to push it down on chrome). commit a1922da927a5eb15d9594a0a517f1f0494aa2fc9

Could you please see if this an improvement?

**Comment by tvb** [comment]
Fixed for me!

**Comment by meeuw** [comment]
nice, thanks for testing!
